# Model Configuration
model:
  sample_rate: 44100
  n_fft: 2048
  hop_length: 512
  vae_latent_dim: 64
  vae_downsample_factor: 16
  diffusion_steps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  unet_channels: 128
  unet_channel_mult: [1, 2, 4, 8]
  attention_resolutions: [32, 16, 8]
  text_encoder_dim: 768
  max_text_length: 256
  vocal_encoder_dim: 512
  accomp_encoder_dim: 512

# Training Configuration
training:
  batch_size: 8
  learning_rate: 1e-4
  weight_decay: 0.01
  num_epochs: 1000
  gradient_clip_norm: 1.0
  save_every: 50
  log_every: 10
  
# Data Configuration
data:
  sample_rate: 44100
  audio_length: 4.0  # seconds
  num_workers: 4
  shuffle: true
